# bug_report.yml
name: バグ報告
description: 不具合報告はこちら
title: 'Bug: '
labels: "bug"
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        不具合の概要を記載してください。
        見た目に関係する場合は、スクリーンショット等を貼り付けてください。
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: 再現環境
      description: |
        再現環境を記載してください。
      options:
          - label: AAA
          - label: BBB
    validations:
      required: false
  - type: checkboxes
    id: roll
    attributes:
      label: ロール
      description: |
        再現するロールを記載してください。
      options:
          - label: 営業担当
          - label: 営業責任者
          - label: 支援責任者
          - label: アンケート事務局
          - label: 稼働率調査事務局
          - label: システム管理者
    validations:
      required: false
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足